require 'active_record/version'
require 'active_record/connection_adapters/abstract_adapter'
require 'java'
require 'arjdbc/jdbc/require_driver'
require 'arjdbc/jdbc/connection_methods'

# Vendor adapters
require 'arjdbc/cachedb'
require 'arjdbc/db2'
require 'arjdbc/derby'
require 'arjdbc/firebird'
require 'arjdbc/h2'
require 'arjdbc/hsqldb'
require 'arjdbc/informix'
require 'arjdbc/mimer'
require 'arjdbc/mssql'
require 'arjdbc/mysql'
require 'arjdbc/oracle'
require 'arjdbc/postgresql'
require 'arjdbc/sqlite3'
require 'arjdbc/sybase'

require 'arjdbc/jdbc/adapter_java'
require 'arjdbc/jdbc/adapter'
require 'bigdecimal'
