require 'active_record/version'
require 'active_record/connection_adapters/abstract_adapter'
require 'arjdbc/jdbc/require_driver'
require 'arjdbc/jdbc/connection_methods'
require 'arjdbc/jdbc/extension'
require 'arjdbc/jdbc/discover'
require 'arjdbc/jdbc/adapter'
require 'bigdecimal'
