require 'jdbc_adapter'
require 'rubygems'
require 'models/auto_id'
require 'models/entry'
require 'models/add_not_null_column_to_table'
require 'simple'
require 'has_many_through'
require 'test/unit'
