# This file was generated by the "jdbc" generator, which is provided
# by the activerecord-jdbc-adapter gem.
#
# This file allows the JDBC drivers to be hooked into ActiveRecord
# such that you don't have to change anything else in your Rails
# application.
require 'jdbc_adapter' if defined?(JRUBY_VERSION)
