exclude :test_migrate_set_and_unset_empty_values_for_verbose_and_version_env_vars, "uses sqlite3-ruby API"
exclude :test_migrate_set_and_unset_nonsense_values_for_verbose_and_version_env_vars, "uses sqlite3-ruby API"
