[
  :test_bulk_insert_multiple_table_with_a_multi_statement_query,
  :test_bulk_insert_with_multi_statements_enabled,
  :test_insert_fixture_set_when_max_allowed_packet_is_bigger_than_fixtures_set_size,
  :test_insert_fixtures_set_concat_total_sql_into_a_single_packet_smaller_than_max_allowed_packet,
  :test_insert_fixtures_set_raises_an_error_when_max_allowed_packet_is_smaller_than_fixtures_set_size,
  :test_insert_fixtures_set_split_the_total_sql_into_two_chunks_smaller_than_max_allowed_packet,
].each do |test|
  exclude test, "bulk insert not yet implemented"
end

exclude :test_fixtures_are_set_up_with_database_env_variable, 'tries to load SQLite3 driver'
