exclude :test_bulk_insert_multiple_table_with_a_multi_statement_query, "bulk insert not yet implemented"
exclude :test_bulk_insert_with_multi_statements_enabled, "bulk insert not yet implemented"
exclude :test_insert_fixtures_set_concat_total_sql_into_a_single_packet_smaller_than_max_allowed_packet, "bulk insert not yet implemented"
exclude :test_insert_fixtures_set_raises_an_error_when_max_allowed_packet_is_smaller_than_fixtures_set_size, "bulk insert not yet implemented"
