MANIFEST = FileList["Manifest.txt", "Rakefile", "README.txt", "LICENSE.txt", "lib/**/*"]

file "Manifest.txt" => :manifest
task :manifest do
  File.open("Manifest.txt", "w") {|f| MANIFEST.each {|n| f << "#{n}\n"} }
end
Rake::Task['manifest'].invoke # Always regen manifest, so Hoe has up-to-date list of files

$LOAD_PATH << "lib"
require "jdbc/sqlite3"
begin
  require 'hoe'
  Hoe.new("jdbc-sqlite3", Jdbc::SQLite::VERSION) do |p|
    p.rubyforge_name = "jruby-extras"
    p.url = "http://jruby-extras.rubyforge.org/ActiveRecord-JDBC"
    p.author = "Nick Sieger, Ola Bini and JRuby contributors"
    p.email = "nick@nicksieger.com, ola.bini@gmail.com"
    p.summary = "SQLite JDBC driver for Java and SQLite/ActiveRecord-JDBC."
    p.changes = "Updated to SQLite version #{Jdbc::SQLite::VERSION}."
    p.description = "Install this gem and require 'sqlite' within JRuby to load the driver."
  end.spec.dependencies.delete_if { |dep| dep.name == "hoe" }
rescue LoadError
  puts "You really need Hoe installed to be able to package this gem"
rescue => e
  puts "ignoring error while loading hoe: #{e.to_s}"
end
