MANIFEST = FileList["Manifest.txt", "Rakefile", "README.txt", "LICENSE.txt", "lib/**/*"]

file "Manifest.txt" => :manifest
task :manifest do
  File.open("Manifest.txt", "w") {|f| MANIFEST.each {|n| f << "#{n}\n"} }
end
Rake::Task['manifest'].invoke # Always regen manifest, so Hoe has up-to-date list of files

$LOAD_PATH << "lib"
require "jdbc/derby"
begin
  require 'hoe'
  Hoe.plugin :gemcutter
  Hoe.spec("jdbc-derby") do |p|
    p.version = Jdbc::Derby::VERSION
    p.spec_extras[:platform] = Gem::Platform.new("java")
    p.rubyforge_name = "jruby-extras"
    p.url = "http://jruby-extras.rubyforge.org/ActiveRecord-JDBC"
    p.author = "Nick Sieger, Ola Bini and JRuby contributors"
    p.email = "nick@nicksieger.com, ola.bini@gmail.com"
    p.summary = "Derby/JavaDB JDBC driver for Java and Derby/ActiveRecord-JDBC."
    p.changes = "Updated to Derby version #{Jdbc::Derby::VERSION}."
    p.description = "Install this gem and require 'derby' within JRuby to load the driver."
  end.spec.dependencies.delete_if { |dep| dep.name == "hoe" }
rescue LoadError
  puts "You really need Hoe installed to be able to package this gem"
rescue => e
  puts "ignoring error while loading hoe: #{e.to_s}"
end
