MANIFEST = FileList["Manifest.txt", "Rakefile", "README.txt", "LICENSE.txt", "lib/**/*"]

file "Manifest.txt" => :manifest
task :manifest do
  File.open("Manifest.txt", "w") {|f| MANIFEST.each {|n| f << "#{n}\n"} }
end
Rake::Task['manifest'].invoke # Always regen manifest, so Hoe has up-to-date list of files

$LOAD_PATH << "lib"
require "jdbc/jtds"
begin
  require 'hoe'
  Hoe.plugin :gemcutter
  Hoe.plugin :rubyforge
  Hoe.spec("jdbc-jtds") do |p|
    version = Jdbc::JTDS::VERSION
    version += '.' + ENV['DRIVER_REV'] if ENV['DRIVER_REV']
    p.version = version
    p.rubyforge_name = "jruby-extras"
    p.url = "http://jruby-extras.rubyforge.org/ActiveRecord-JDBC"
    p.author = "Nick Sieger, Ola Bini and JRuby contributors"
    p.email = "nick@nicksieger.com, ola.bini@gmail.com"
    p.summary = "jTDS JDBC driver for Java and jTDS/ActiveRecord-JDBC."
    p.changes = "Updated to jTDS version #{Jdbc::JTDS::VERSION}."
    p.description = "Install this gem and require 'jtds' within JRuby to load the driver."
  end.spec.dependencies.delete_if { |dep| dep.name == "hoe" }
rescue LoadError
  puts "You really need Hoe installed to be able to package this gem"
rescue => e
  puts "ignoring error while loading hoe: #{e.to_s}"
end
